name: continuous-integration

on:
  push:
    branches:
      - main
    tags:
      - 'v*'
    paths:
      - 'src/**'
      - 'pyproject.toml'
      - '.python-version'
      - '.github/workflows/ci.yml'

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v5

      - name: Install the project
        run: |
          uv sync --all-extras --dev

      - name: Run Lint
        run: |
          uvx ruff check

      - name: Install package for testing
        run: |
          pip install -e .

      - name: Run tests and generate JUnit XML
        run: |
          pip install pytest
          pytest --junitxml=pytest-results.xml

      - name: Upload test results
        uses: actions/upload-artifact@v4
        with:
          name: pytest-results
          path: pytest-results.xml

      - name: Publish Test Results
        uses: EnricoMi/publish-unit-test-result-action@v2
        if: always()
        with:
          files: pytest-results.xml

      - name: Build distribution
        run: |
          uv build

      - name: Check distribution with twine
        run: |
          uvx twine check dist/*