name: continuous-integration

on:
  push:
    branches:
      - main
    tags:
      - 'v*'
    paths:
      - 'src/**'
      - 'pyproject.toml'
      - '.python-version'
      - '.github/workflows/ci.yml'

permissions:
  contents: read
  actions: read
  checks: write

jobs:
  build-and-publish:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v5

      - name: Install dependencies (dev + extras)
        run: uv sync --all-extras --dev

      - name: Run linter
        run: uvx ruff check

      - name: Build distribution
        run: uv build

      - name: Check distribution with twine
        run: uvx twine check dist/*

      - name: Install package for testing
        run: |
          pip install -e .

      - name: Run tests with coverage and JUnit output
        run: |
          pip install -r .devcontainer/requirements_dev.txt
          pytest \
            --junit-xml=pytest-results.xml \
            --cov=src \
            --cov-report=xml \
            --cov-report=term \
            --cov-fail-under=100 \
            > test_output.txt

      - name: Upload test results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: pytest-results
          path: pytest-results.xml

      - name: Upload coverage report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: coverage-report
          path: coverage.xml

      - name: Publish test results
        uses: EnricoMi/publish-unit-test-result-action@v2
        if: always()
        with:
          files: pytest-results.xml

      - name: Write test summary to GitHub Actions UI
        if: always()
        run: |
          echo "## 🧪 Test Results and Coverage" >> $GITHUB_STEP_SUMMARY
          echo "\`\`\`" >> $GITHUB_STEP_SUMMARY
          cat test_output.txt >> $GITHUB_STEP_SUMMARY
          echo "\`\`\`" >> $GITHUB_STEP_SUMMARY

      - name: Write coverage summary to GitHub Actions UI
        if: always()
        run: |
          echo "## 📊 Coverage Report" >> $GITHUB_STEP_SUMMARY
          echo "\`\`\`" >> $GITHUB_STEP_SUMMARY
          uvx coverage report --show-missing >> $GITHUB_STEP_SUMMARY
          echo "\`\`\`" >> $GITHUB_STEP_SUMMARY